connectedcars/node-test

- src/unix/run-process.ts
When calling .kill on a process which is not running
(which might not be apparant), an empty Error is just shown in node.
Same instance with timeouts when waiting for exit and nothing happens.
> Add error messages in run-process

- src/unix/run-process.test.ts
- src/unix/run-process.ts
When running RunProcess waitForOutput will have a asynchronous setTimeOut
waiting in the background, which didn't get cleared if the output wasn't found
but the process still exited.
> run-process: fix timeout hanging on waitForExit

- bin/checks.ts
- src/checks/jest/jest.ts
`name` was changing during run:
> CRA jest should maintain the name for checks output

- bin/checks.ts
Otherwise running e.g. `checks --version` or `checks --help` requires setting the `COMMIT_SHA` variable.
> Moved commit sha check

- bin/checks.ts
- src/checks/cargo/run-cargo-check.ts
Discovered the other day that feature-gated code wasn't always linted correctly.
-----
If `--all-features` was set vs unset, then it would yield different lints. So if you for instance had:
```
#[cfg(feature = "mock")]
use std::collections::HashMap;
```
Then assuming `HashMap` is an unused import, then it would ofc not lint without `--all-features`, but it would lint with `--all-features` as expected.
However, if we invert the condition like this:
```
#[cfg(not(feature = "mock"))]
use std::collections::HashMap;
```
Then again assuming it's an unused import, then it would lint without `--all-features`. However, it **wouldn't** emit the lint with `--all-features`, which was the issue as we always used `--all-features`. We couldn't just remove it, as then we'd no longer get a majority of …
> Fixed cargo check for feature-gated code

- bin/checks.ts
- src/checks/cargo/cargo.ts
If `checks` is executed with `--ci`, then the `RUSTFLAGS` env var is appended with `CI_RUSTFLAGS`. If `CI_RUSTFLAGS` is not set, then it by default uses `-F warnings -D unused` to be able to forbid and deny any and every instance of `#[allow(warnings)]` and `#[allow(unused)]`.
For clarity, the reason we want to disallow those, is that using either of those two, is a blanket allow for many lints. So if someone wants to e.g. keep an unused import, then it's better to do `#[allow(unused_imports)]` as it only allows _that_, while with `#[allow(unused)]` you'll _accidentally_ allow a lot more.
Basically, we want to avoid needing to do stuff like this https://github.com/connectedcars/firmware_hal/pull/419 specifically this in [nebula.rs](https://github.com/connectedcars/firmware_hal/blob/ed5a66f …
> Update RUSTFLAGS if CI to forbid any blanket allow warnings

- bin/checks.ts
- src/checks/cargo/cargo.ts
- src/checks/cargo/run-cargo-check.ts
- src/checks/cargo/run-cargo-clippy.ts
- src/checks/cargo/run-cargo-fmt.ts
- src/checks/cargo/run-cargo-test.ts
- src/checks/cargo/run-cargo.ts
Resolved the issue. Now it instead passes a new associate array, with a shallow clone of the remaining entries of `process.env`.
~(Attempted to make `runCargo` generic, so it could be used for `runCargoFmt` as well, but it gave some weird runtime errors, while none at _compile_ time)~
[[ch-55542](https://app.clubhouse.io/connectedcars/story/55542/pass-env-to-child-process-instead-of-overriding-global-env-vars)]
> Reworked Rust checks to pass env to child process

- bin/checks.ts
Changed to only require `COMMIT_SHA` if `--ci`. All CIs are using `--ci`, so this should be fine.
It's _only_ to remove a minor annoyance of needing to do `export COMMIT_SHA="dummy"` when opening a terminal (without having it defined in e.g. .bashrc).
(There's another issue I want to look at too, so a new release can wait)
[[ch-56655](https://app.clubhouse.io/connectedcars/story/56655/only-require-commit-sha-if-ci)]
> Changed to only require COMMIT_SHA if --ci

- bin/checks.ts
- src/checks/cargo/run-cargo-test.ts
Fixed so `checks cargo-test` now runs doc tests. Apparently `--all-targets` and `--doc` does not mix, so it needs to run `cargo test` twice.
[[sc-62453](https://app.shortcut.com/connectedcars/story/62453/rust-checks-skips-doc-tests)]
> Fixed cargo test not running doc tests

- bin/checks.ts
- src/checks/cargo/run-cargo-check.ts
[[sc-64429](https://app.shortcut.com/connectedcars/story/64429/rust-checks-fail-to-catch-non-debug-lints)]
> Added check for Rust release build

- src/checks/cargo/cargo.ts
This is safe to merge. While it is related to bumping to Rust 1.54, it does not affect using the Rust checks with Rust 1.49.
Related: [[sc-64076](https://app.shortcut.com/connectedcars/story/64076/bump-rust-1-54)]
Related: [[sc-63760](https://app.shortcut.com/connectedcars/story/63760/rust-checks-produce-broken-output-and-cause-ci-to-fail)]
> Fixed RUSTFLAGS for Rust 1.54

- bin/checks.ts
- src/checks/cargo/run-cargo-clippy.ts
[[sc-64429](https://app.shortcut.com/connectedcars/story/64429/rust-checks-fail-to-catch-non-debug-lints)]
> Added check for Clippy release build

- bin/checks.ts
- src/checks/cargo/cargo.ts
- src/checks/cargo/run-cargo-locate-workspace.ts
- src/checks/cargo/run-cargo.ts
[[sc-64454](https://app.shortcut.com/connectedcars/story/64454/rust-checks-build-into-different-target-dirs)]
Partially: [[sc-61799](https://app.shortcut.com/connectedcars/story/61799/checks-cargo-clippy-always-rebuilds-all-dependencies)]
> Minimized when recompilation is triggered for Rust

- bin/checks.ts
- src/checks/cargo/cargo-check.ts
- src/checks/cargo/cargo-clippy.ts
- src/checks/cargo/cargo-fmt.ts
- src/checks/cargo/cargo-test.ts
- src/checks/cargo/cargo-types.ts
- src/checks/cargo/cargo.ts
- src/common.ts
[[sc-65915](https://app.shortcut.com/connectedcars/story/65915/rust-checks-are-not-skipped-if-cargo-toml-has-issues)]
> Fixed to handle manifest parse errors

- src/checks/cargo/cargo-check.ts
- src/checks/cargo/cargo-clippy.ts
- src/checks/cargo/cargo-fmt.ts
- src/checks/cargo/cargo-test.ts
- src/checks/cargo/cargo.ts
- src/checks/cargo/run-cargo-clippy.ts
- src/checks/cargo/run-cargo.ts
No behavioral changes, only streamlined all checking logic across all Rust checks
[[sc-66207](https://app.shortcut.com/connectedcars/story/66207/streamline-rust-checks-implementations)]
> Streamlined Rust checks

- bin/checks.ts
- src/checks/cargo/cargo-sort.ts
- src/checks/cargo/run-cargo-locate-workspace.ts
- src/checks/cargo/run-cargo-sort.ts
- src/checks/cargo/run-cargo.ts
- src/checks/checks-common.ts
- src/checks/tsc/run-tsc.ts
- src/common.ts
- src/mysql/mysqld-utils.ts
- src/unix/linux.ts
Implemented a new Rust manifest check that uses `cargo sort`. This requires `cargo-sort` to be installed, so currently it is not enabled by default.
[[sc-65744](https://app.shortcut.com/connectedcars/story/65744/rust-check-for-dependency-order)]
> Implemented Rust manifest check

- src/checks/cargo/__snapshots__/cargo-check.test.ts.snap
- src/checks/cargo/__snapshots__/cargo-clippy.test.ts.snap
- src/checks/cargo/__snapshots__/cargo-fmt.test.ts.snap
- src/checks/cargo/__snapshots__/cargo-test.test.ts.snap
- src/checks/cargo/cargo-check.ts
- src/checks/cargo/cargo-clippy.ts
- src/checks/cargo/cargo-fmt.ts
- src/checks/cargo/cargo-sort.ts
- src/checks/cargo/cargo-test.ts
- src/checks/cargo/cargo.ts
Streamlined the output returned by all (Rust) checks.
[[sc-66207](https://app.shortcut.com/connectedcars/story/66207/streamline-rust-checks-implementations)]
> Streamlined duplicate code for check result

- bin/checks.ts
- src/checks/cargo/run-cargo.ts
- Fixes issue with CLI flags, where they default to `undefined` instead of `false`. Which results in unexpected values, when passed to functions with default parameter values of `true`
- Added `cc_build` cfg attrib
- Added `cc_ci_build` cfg attrib, as an alternative to `ci_build`
- Added `CC_CI_RUSTFLAGS` env var, as an alternative to `CI_RUSTFLAGS`
Fixes: [[sc-71135](https://app.shortcut.com/connectedcars/story/71135/checks-confuses-ci-and-local-runs)]
Related: [[sc-65972](https://app.shortcut.com/connectedcars/story/65972/firmware-hal-create-lint-to-force-env-logger-and-disable-println)]
> Fixed ci flag and added cfg attribs

- src/mysql/mysqld-utils.ts
If you start up `npm run local-mysql`, and you don't set TZ, it will use system time
> Default to UTC tz

- src/mysql/migrate.ts
[sc-88791] [skip-sc]
Some production tables simply take too long to migrate and would meanwhile break our services because it likely needs to take some exclusive locks at some point.
Instead, we add them to the skip list and revert the data migrations on the data repo (the latter in order to keep data as a correct view of the actual tables in both staging and production).
Once merged and bumped, the new version will be updated in connectedcars/data#1045.
> Skip charset/collation checks on some prod tables

- src/mysql/migrate.ts
[sc-88791] [skip-sc]
Data builds/passes with `npm link` now. Api builds with `npm link`ed data repo.
> Add missing entry in skip list

- src/mysql/__snapshots__/mysqld-utils.test.ts.snap
- src/mysql/mysqld-utils.ts
[sc-122171][skip-sc]
- Turns out that the max connections for non mac has been the default `151` which causes us to hit this the connection count error (specially on the API) when running parallel integration tests
- I tested this change on the API and i was able to run the integration tests in parallel in docker
> fix(MySQLServer): increase max_connections for all OS
