connectedcars/node-test

Dockerfile
bin/local-mysql.ts
src/mysql/__snapshots__/mysql-client.test.ts.snap
src/mysql/mysql-client.test.ts
src/mysql/mysql-client.ts

* Add option to only checkout a number of tables in a database
* Fixing an old checkout is a lot smarter, truncating and recopying data for the tables that changed

Optimized checkout

---

Dockerfile
bin/cache-migrations.ts
bin/local-mysql.test.ts
bin/local-mysql.ts
src/mysql/__snapshots__/mysqld-utils.test.ts.snap
src/mysql/migrate.test.ts
src/mysql/mysql-client.test.ts
src/mysql/mysql-server.test.ts
src/mysql/mysql-server.ts
src/mysql/mysqld-utils.test.ts
src/mysql/mysqld-utils.ts
src/unix/process.ts

* Add support for setting MYSQLD environment to use different mysqld
* Add both mysqld 5.7 and 8.0 to same docker image
* Add support for mysqld installed in non hardcoded locations for the binary

Multi mysql install

---

src/checks/jest/jest.test.ts
src/checks/jest/resources/jest-help-text.ts
src/mysql/__snapshots__/mysqld-utils.test.ts.snap
src/mysql/mysqld-utils.ts

* Set default charset and collation to something that is supported on both mysql 5.7 and mysql 8.x
* Disable safety to speed up tests

 Mysql 5.7 and mysql 8.x charset and test speedup

---

src/http/http-server-base.ts

Adds socket destroy on test server cleanup

---

Dockerfile

Bump docker image to node 14

---

src/checks/cargo/cargo.test.ts
src/checks/cargo/cargo.ts
src/checks/cargo/run-cargo-check.test.ts
src/checks/cargo/run-cargo-clippy.test.ts
src/checks/cargo/run-cargo-fmt.ts
src/checks/cargo/run-cargo-test.test.ts
src/checks/cargo/run-cargo.ts
src/checks/cargo/run-rustc-version.ts

[[sc-64615](https://app.shortcut.com/connectedcars/story/64615/rust-checks-remove-touch-cache)]

Added check to avoid needlessly invalidating the cache

---

src/checks/cargo/cargo-clippy.ts
src/checks/cargo/cargo.ts

[[sc-66111](https://app.shortcut.com/connectedcars/story/66111/ci-rustflags-affects-dependencies)]

Fixed to ignore messages from dependencies

---

src/checks/cargo/cargo.ts
src/checks/cargo/run-cargo-locate-workspace.ts

(Needs to be rebased, when #71 has been merged)

Fixed locate workspace to check exit code

---

bin/checks.ts
src/checks/cargo/cargo-check.ts
src/checks/cargo/cargo-clippy.ts

[[sc-66210](https://app.shortcut.com/connectedcars/story/66210/include-other-check-lints-if-other-check-is-not-executed)]

Changed to include all lints if single check is executed

---

src/checks/cargo/run-cargo-clippy.ts

Related: [[sc-64076](https://app.shortcut.com/connectedcars/story/64076/bump-rust-1-54)]

Changed deny to warn to maximize Rust lints

---

Dockerfile
package-lock.json
package.json

chore(): bump node version 16

---

src/checks/mocha/mocha.ts

Fixes stack trace matching in Mocha tests

---

src/checks/jest/jest.ts

fix(Jest): fail on snapshot failure

---

src/checks/jest/__snapshots__/jest.test.ts.snap
src/checks/jest/jest.ts
src/checks/jest/resources/jest-help-text.ts

Adds support for title and line numbers for Jest

---

src/checks/jest/__snapshots__/jest.test.ts.snap
src/checks/jest/jest.test.ts
src/checks/jest/jest.ts
src/checks/jest/resources/jest-help-text.ts

Adds handling of obsolete jest snapshots

---

bin/checks.ts
src/checks/vitest/__snapshots__/vitest.test.ts.snap
src/checks/vitest/resources/vitest-help-text.ts
src/checks/vitest/run-vitest.test.ts
src/checks/vitest/run-vitest.ts
src/checks/vitest/vitest.test.ts
src/checks/vitest/vitest.ts

Add support for vitest

---

src/mysql/migrate.ts

Add filter for only running migrations in specific dirs

---

src/mysql/migrate.ts

Add options dryRun and printStatements to assess what is actually going to run

---

src/mysql/migrate.test.ts
src/mysql/migrate.ts

Fix --dryRun not working when Migrations table has not yet been created

---

src/mysql/migrate.ts

Check for existence of Migrations table instead of just the database

---

src/http/https-server.test.ts
src/http/web-server.test.ts
src/index.ts

Exposes helper to find free port

---

bin/checks.ts

Adds custom check name support to jest

---

bin/checks.ts

Fixes custom checks name

---

src/http/http-server-base.ts
src/mysql/mysqld-utils.ts

refactor(HTTPServer): cleanup for test sever

---

src/http/http-server-base.ts

fix(HTTPServerBase): remove listeners correctly

---

bin/checks.ts
src/checks/tflint/__snapshots__/tflint.test.ts.snap
src/checks/tflint/resources/tflint-issues.ts
src/checks/tflint/run-tflint.test.ts
src/checks/tflint/run-tflint.ts
src/checks/tflint/tflint.test.ts
src/checks/tflint/tflint.ts

Adds tflint check

---

src/mysql/migrate.test.ts
src/mysql/migrate.ts
src/mysql/resources/ignore-timestamp-in-comment/databases.json
src/mysql/resources/ignore-timestamp-in-comment/test/2024-06-12T095700_TimestampInComment.sql

Updates timestamp checks to ignore SQL comments

---

bin/local-mysql.ts
src/mysql/migrate.test.ts
src/mysql/migrate.ts

Adds option for skipping of all migration checks

---

src/mysql/migrate.ts

Exposes databaseMap to use in data repo

---

bin/checks.ts
src/checks/tsc/run-tsc.ts

Adds custom args option to tsc check

---

src/http/http-server.ts
src/http/https-server.ts

Switches default host from localhost to 127.0.0.1

---

src/checks/jest/jest.test.ts
src/checks/jest/jest.ts

refactor(jestCheck): try to truncate message

---

src/http/__snapshots__/http-server.test.ts.snap
src/http/http-server-base.ts
src/http/http-server.test.ts

Fix broken request saving logic

---

package-lock.json
package.json
src/http/http-common.ts
src/http/http-server.test.ts

Fixes request body parsing to only read once

---

src/index.ts
src/mysql/mysql-client.ts
src/unix/errors.ts

Move mysql client and migration tool to node-dba
